### ISSUE TITLE
Title: Improve the Ui of the careers roadmap section in dark-mode

### ISSUE THREAD

**Issue by Himanshu-kumar025** [ayush-that/FinVeda#1678]
### Is your feature request related to a problem? Please describe.

UI of careers roadmap section in dark mode in not that good .I would like to work on this issue.

### Describe the solution you'd like.

Improve the UI of the  careers roadmap section in dark mode . So user experience become more engaging.

### Describe alternatives you've considered.

Improving the Ui of the roadmap section

### Add any other context or screenshots about the feature request here.

![Screenshot 2024-10-20 190544](https://github.com/user-attachments/assets/889b6416-500e-47e6-8620-81523f066052)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

**Comment by 20username11** [comment]
I want to contribute to this project please assing me this project
