### ISSUE TITLE
Title: Update Meta Tags for improved SEO and social sharing.

### ISSUE THREAD

**Issue by neeru24** [ayush-that/FinVeda#2197]
### Is your feature request related to a problem? Please describe.

The meta title and description for the FinVeda homepage need to be updated to improve SEO and attract more visitors.

### Describe the solution you'd like.

- Revise the meta title to include relevant keywords for UI design.
- Update the meta description to reflect the homepage content and include targeted keywords.

### Describe alternatives you've considered.

This can be efficiently accomplished by simply adding relevant keywords to the existing meta title and description in the HTML code.

By optimizing these meta tags, we can improve the website’s search engine visibility and attract more visitors.

### Add any other context or screenshots about the feature request here.

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue
